### ISSUE TITLE
Connection issue  on Github actions

### ISSUE THREAD

**Issue by hantsy** [gvenzl/oci-oracle-free#33]
I have tried to use https://github.com/marketplace/actions/setup-oracle-db-free and custom docker compose to serve an oracle db, when connecting to db against `localhost` host, I got the error like this:

```
 Caused by: org.hibernate.service.spi.ServiceException: 
Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] 
due to: io.vertx.oracleclient.OracleException: ORA-17868: 
Unknown host specified.: oracle: Temporary failure in name resolution
```

The Github task I have tried like this.

```yaml
- uses: gvenzl/setup-oracle-free@v1
 with:
   oracle-database: blogdb
   app-user: testUser
   app-user-password: testPassword    
```

And the docker compose file use this docker image like this.

```yaml
version: '3.7' # specify docker-compose version

services:
  oracle:
    # see https://www.oracle.com/database/technologies/appdev/xe.html
    image: gvenzl/oracle-free:23-slim
    ports:
      - "1521:1521"
    restart: always
    environment:
      ORACLE_PASSWORD: sysPassword
      ORACLE_DATABASE: blogdb
      APP_USER: testUser
      APP_USER_PASSWORD: testPassword
    volumes:
      - ./data:/opt/oracle/oradata
```

And Github actions step to call it.

```yml
- name: Set up Oracle(via Docker Compose)
  run: |
    cd hibernate-reactive-mutiny-oracle
    docker-compose up -d
    sleep 10
    docker ps -a

```

The JDBC URL I used to connect this db is `jdbc:oracle:thin://localhost:1521/blogdb`.

**Comment by gvenzl** [comment]
Hi @hantsy,

Thanks for using these images!

I just tried to reproduce this with GitHub Actions but I do not get any errors.

Here is the GitHub Actions yaml:

```
name: SQLcl
run-name: Test SQLcl in GitHub Actions 🚀
on: [push]
jobs:
  setup-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gvenzl/setup-oracle-free@v1
        with:
          app-user: testUser
          app-user-password: testPassword
          oracle-database: blogdb
          tag: slim
      - uses: gvenzl/setup-oracle-sqlcl@v1
      - name: Run SQLcl
        run: |
          echo "SELECT 'Hey there!';" | sql testUser/testPassword@localhost:1521/blogdb
```

And here the successful GitHub actions run:

<img width="883" alt="image" src="https://github.com/user-attachments/assets/87c8669f-bb90-4500-ae63-992cfc584f8b">

Is this still an issue at your end?
