### ISSUE TITLE
Configuration needed for oracle-free:23.6-faststart on GitLab CI?

### ISSUE THREAD

**Issue by jeffjensen** [gvenzl/oci-oracle-free#82]
Hi, 

Is there anything additional needed to make oracle-free:23.6-faststart work on GitLab CI?  I've searched and tried so many things but not found the magic combination.  This is my base:
```
  services:
    - name: gvenzl/oracle-free:23.6-faststart
      alias: oracle23
      variables:
        TZ: America/Chicago
        ORACLE_PASSWORD: dbunit
        APP_USER: dbunit
        APP_USER_PASSWORD: dbunit
```
Error is
> SQLRecoverable Listener refused the connection with the following error: ORA-12514, TNS:listener does not currently know of service requested in connect descriptor

The connection string is `jdbc:oracle:thin:@oracle23:1521/FREEPDB1`.

It's as if it does not create FREEPDB1.
If I set ORACLE_DATABASE it doesn't seem to create that either.

When I run the image locally with those values it work and starts.  Locally, I also see in the startup log additional messages like
> ORACLE instance started.
> CONTAINER: Resetting SYS and SYSTEM passwords.
> CONTAINER: Creating app user for default pluggable database.

But, in GitLab CI, no further messages seen after "The command completed successfully" (not sure if that's normal/rest are hidden or a symptom).  Makes me think additional configuration needed in the GL CI environment to make it happen?
