### ISSUE TITLE
Errors on startup with persistent volumes

### ISSUE THREAD

**Issue by slawrence-miso** [gvenzl/oci-oracle-free#83]
I have been seeing an issue with persisting the DB onto a docker bind volume after a "docker compose down". 

 oracle │ 2025-02-06T22:02:21.339415+00:00
       oracle │ Errors in file /opt/oracle/diag/rdbms/free/FREE/trace/FREE_mz00_3797.trc:
       oracle │ ORA-01110: data file 24: '/opt/oracle/product/23ai/dbhomeFree/dbs/DATA'
       oracle │ ORA-01565: Error identifying file /opt/oracle/product/23ai/dbhomeFree/dbs/DATA.
       oracle │ ORA-27037: unable to obtain file status
       oracle │ Linux-x86_64 Error: 2: No such file or directory
       oracle │ Additional information: 7

It seems like this file is ephemeral or something and isn't being saved in my volume?

**Comment by gvenzl** [comment]
Hi @slawrence-miso,

Thanks for using these images!

Hm, this does look indeed like the volume has disappeared, as indicated by `Linux-x86_64 Error: 2: No such file or directory`.

Not being an expert in Docker Compose myself, can it be that the volume has been removed prior to the container being fully stopped?

**Comment by aledv** [comment]
Hi All, I'm wrote this docker-compose.yml:

```
version: "3.8"
services:
  oracle:
    image: gvenzl/oracle-free:latest
    platform: linux/arm64 # Aggiunta per Raspberry Pi
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: xxx
      APP_USER: xxx
      APP_USER_PASSWORD: xxx
    healthcheck:
      test: ["CMD", "healthcheck.sh"] # Assicurati che healthcheck.sh esista nel container
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s
    volumes:
      - /mnt/external_hd/oracle/my-init.sql:/container-entrypoint-initdb.d/my-init.sql:ro
      - /mnt/external_hd/oracle/oradata:/opt/oracle/oradata 
    networks:
      - oracle-network
    user: ${UID}:${GID} # Permessi corretti per il volume dati
    shm_size: 1g # Dimensione della shared memory (consigliata per Oracle)
    restart: unless-stopped # Riavvia in caso di problemi

networks:
  oracle-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.14.0.0/24
```


I'm encountering an error that prevents the container from starting.

```
CONTAINER: starting up...
CONTAINER: first database startup, initializing...
CONTAINER: uncompressing database data files, please wait...
ERROR: Cannot create folder : errno=13 : Permission denied : /opt/oracle/oradata/FREE
ERROR: Cannot create folder : errno=2 : No such file or directory : /opt/oracle/oradata/FREE/FREEPDB1
ERROR: Cannot create folder : errno=2 : No such file or directory : /opt/oracle/oradata/FREE/pdbseed
ERROR: Cannot open output file : errno=2 : No such file or directory : /opt/oracle/oradata/FREE/FREEPDB1/sysaux01.dbf
```
